### ISSUE TITLE
[ENHANCEMENT] WingPanel indicator

### ISSUE THREAD

**Issue by pavel-kalmykov** [aimproxy/PomodoroApp#15]
**Is your feature request related to a problem? Please describe.**
No. Right now the App seems to work fine.

**Describe the solution you'd like**
It would be great to have the same functionality but from the Wingpanel. Or at least to be able to check the running time from it.

**Comment by aimproxy** [comment]
Hi, it's seems elementary os apps are dying, not every one maintain eOS apps, flathub is a more popular store! If u wanna implement ur idea, ur fine, just make a PR, it's an easy implementation to do! 

I will probably merge this project into flathub!
